base_model: # <Janus* 7b (66k) checkpoint>
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

rl: dpo
datasets:
  - path: data/train/multifaceted_collection_dpo.jsonl
    type:
      field_prompt: instruction
      field_system: system
      field_chosen: chosen_response
      field_rejected: rejected_response
      prompt_format: "[INST] {system}\n{instruction} [/INST]"
      chosen_format: {chosen_response}
      rejected_format: {rejected_response}
      
dataset_prepared_path:
hub_model_id: 
hub_strategy: checkpoint
# val_set_size: 0
output_dir: 

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true
eval_sample_packing: false

wandb_project: 
wandb_entity: 
wandb_watch:
wandb_name: 
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0000005

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
# evals_per_epoch: 4
eval_table_size:
# eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
